# ============================================================
# FPGS package illustration
# Binary outcome: Hypertension
# Treatment: Smoking
# ============================================================

### Load required packages
library(dplyr)
library(FPGS)

### Read data
datat <- read.csv(
  "C:/Users/chapo752/Dropbox/PhD work- Chamika Porage/Paper3_Disease risk score/Simulation_study/Simulation_new/Empirical analysis/df.csv"
)

### Inspect outcome and treatment variables

table(datat$HTN, useNA = "ifany")
table(datat$smoking, useNA = "ifany")

### Covariate matrix

X <- model.matrix(
  ~ gender +
    age +
    race +
    army.service +
    edu +
    married.living.with.partner +
    income.to.poverty +
    birth.country +
    family.size,
  data = datat
)



### Remove the intercept generated by model.matrix()

# model.matrix() automatically includes an intercept column.
# This must be removed because the regression models fitted
# inside fpgs() include their own intercept.

X <- X[
  ,
  colnames(X) != "(Intercept)",
  drop = FALSE
]

# Check that no intercept remains
colnames(X)
dim(X)

### Remove linearly dependent covariate columns

# The FPGS is estimated using separate outcome models in the
# treated and untreated groups. Therefore, the covariate matrix
# should have full column rank in both groups.
#
# This function retains columns that are linearly independent
# in:
#   (1) the complete sample,
#   (2) the treated group, and
#   (3) the untreated group.

make_group_full_rank <- function(X, treatment, tol = 1e-7) {

  q_all <- qr(
    X,
    tol = tol
  )

  q_1 <- qr(
    X[treatment == 1, , drop = FALSE],
    tol = tol
  )

  q_0 <- qr(
    X[treatment == 0, , drop = FALSE],
    tol = tol
  )

  keep <- Reduce(
    intersect,
    list(
      q_all$pivot[seq_len(q_all$rank)],
      q_1$pivot[seq_len(q_1$rank)],
      q_0$pivot[seq_len(q_0$rank)]
    )
  )

  X[, sort(keep), drop = FALSE]
}


# Apply the full-rank procedure
X <- make_group_full_rank(
  X = X,
  treatment = datat$smoking
)

# Check rank of the resulting covariate matrix

# Number of retained covariates
ncol(X)

# Rank in the complete sample
qr(X)$rank

# Rank among untreated individuals
qr(
  X[datat$smoking == 0, , drop = FALSE]
)$rank

# Rank among treated individuals
qr(
  X[datat$smoking == 1, , drop = FALSE]
)$rank

### Covariates simple names

colnames(X) <- paste0(
  "x",
  seq_len(ncol(X))
)

colnames(X)

### Construct analysis dataset


df_bin <- data.frame(
  HTN = datat$HTN,
  smoking = datat$smoking,
  X,
  check.names = FALSE
)

### Inspect analysis dataset
dim(df_bin)

head(df_bin)

# Outcome distribution
table(df_bin$HTN)

# Treatment distribution
table(df_bin$smoking)

# Cross-tabulation of outcome and treatment
table(
  Outcome = df_bin$HTN,
  Treatment = df_bin$smoking
)

# Checking for missing values
colSums(
  is.na(df_bin)
)

### Remove incomplete observations (if necessary)

df_bin <- na.omit(df_bin)

dim(df_bin)

table(df_bin$HTN)
table(df_bin$smoking)

### Define covariates used by FPGS

covariates_bin <- setdiff(
  names(df_bin),
  c("HTN", "smoking")
)

length(covariates_bin)

covariates_bin

### FIRST-STAGE LOGISTIC REGRESSION MODELS###


form_bin <- reformulate(
  covariates_bin,
  response = "HTN"
)

form_bin

### Fit model among untreated individuals

mod0_check <- glm(
  form_bin,
  data = df_bin[df_bin$smoking == 0, ],
  family = binomial()
)

### Fit model among treated individuals

mod1_check <- glm(
  form_bin,
  data = df_bin[df_bin$smoking == 1, ],
  family = binomial()
)

### Check for unidentified coefficients

# These should both return FALSE
anyNA(coef(mod0_check))
anyNA(coef(mod1_check))

# These should both return named numeric(0)
coef(mod0_check)[
  is.na(coef(mod0_check))
]

coef(mod1_check)[
  is.na(coef(mod1_check))
]

### Additional rank checks for the actual regression design matrices

X0_check <- model.matrix(mod0_check)
X1_check <- model.matrix(mod1_check)

c(
  n_columns = ncol(X0_check),
  rank = qr(X0_check)$rank
)

c(
  n_columns = ncol(X1_check),
  rank = qr(X1_check)$rank
)

# For both models: rank should equal n_columns.

### LOGISTIC-REGRESSION FPGS

### Estimate FPGS

fit_bin <- fpgs(
  data = df_bin,
  outcome = "HTN",
  treatment = "smoking",
  covariates = covariates_bin,
  outcome_type = "binary",
  method = "logistic_regression"
)

fit_bin

### Check estimated FPGS components

summary(fit_bin$mu0_hat)
summary(fit_bin$mu1_hat)

length(fit_bin$mu0_hat)
length(fit_bin$mu1_hat)

anyNA(fit_bin$mu0_hat)
anyNA(fit_bin$mu1_hat)

# Since the outcome is binary, the FPGS components are
# estimated probabilities and should lie between 0 and 1.

range(fit_bin$mu0_hat)
range(fit_bin$mu1_hat)

### PART B: POINT ESTIMATION###

### Estimate ATE using all six estimators

ate_bin <- fpgs_ate(
  fit = fit_bin,
  variance = "none"
)

ate_bin

### ANALYTIC VARIANCE ESTIMATION

### Obtain analytic variance estimates

ate_bin_analytic <- fpgs_ate(
  fit = fit_bin,
  variance = "analytic"
)

ate_bin_analytic

### Basic checks of analytic results

names(ate_bin_analytic)

all(
  is.finite(ate_bin_analytic$estimate)
)

all(
  ate_bin_analytic$variance >= 0,
  na.rm = TRUE
)

all(
  ate_bin_analytic$se >= 0,
  na.rm = TRUE
)

### BOOTSTRAP INFERENCE###

### Bootstrap variance estimation

set.seed(2026)

ate_bin_boot <- fpgs_ate(
  fit = fit_bin,
  variance = "bootstrap",
  B = 1000,
  conf.level = 0.95
)

ate_bin_boot

### RANDOM-FOREST FPGS

### Estimate FPGS using random forest

fit_bin_rf <- fpgs(
  data = df_bin,
  outcome = "HTN",
  treatment = "smoking",
  covariates = covariates_bin,
  outcome_type = "binary",
  method = "random_forest",
  folds = 5
)

fit_bin_rf

### Random-forest FPGS components


summary(fit_bin_rf$mu0_hat)
summary(fit_bin_rf$mu1_hat)

length(fit_bin_rf$mu0_hat)
length(fit_bin_rf$mu1_hat)

anyNA(fit_bin_rf$mu0_hat)
anyNA(fit_bin_rf$mu1_hat)

range(fit_bin_rf$mu0_hat)
range(fit_bin_rf$mu1_hat)

### Point estimates using random-forest FPGS

ate_bin_rf <- fpgs_ate(
  fit = fit_bin_rf,
  variance = "none"
)

ate_bin_rf

###COMPARE LOGISTIC REGRESSION AND RANDOM FOREST

comparison_bin <- data.frame(
  estimator = ate_bin$estimator,
  logistic_regression = ate_bin$estimate,
  random_forest = ate_bin_rf$estimate
)

comparison_bin


### COMPUTATION TIME FOR BOOTSTRAP INFERENCE

# This section compares computation time for bootstrap
# inference when the FPGS is estimated using:
#   (1) logistic regression
#   (2) random forest with cross-fitting

### Number of bootstrap replications for timing

B_time <- 1000

### LOGISTIC-REGRESSION FPGS

# Bootstrap inference: logistic-regression FPGS

time_logistic_boot <- system.time({

  ate_bin_boot_time <- fpgs_ate(
    fit = fit_bin,
    variance = "bootstrap",
    B = B_time,
    conf.level = 0.95
  )

})

# Logistic-regression results and computation time


ate_bin_boot_time

time_logistic_boot

cat(
  "\nElapsed time for logistic-regression bootstrap:",
  time_logistic_boot["elapsed"],
  "seconds\n"
)


# ============================================================
# RANDOM-FOREST FPGS
# ============================================================

### Bootstrap inference: random-forest FPGS

time_rf_boot <- system.time({

  ate_bin_rf_boot_time <- fpgs_ate(
    fit = fit_bin_rf,
    variance = "bootstrap",
    B = B_time,
    conf.level = 0.95
  )

})

### Random-forest results and computation time


ate_bin_rf_boot_time

time_rf_boot

cat(
  "\nElapsed time for random-forest bootstrap:",
  time_rf_boot["elapsed"],
  "seconds\n"
)



# COMPARING COMPUTATION TIMES

### Construct timing comparison


timing_comparison <- data.frame(
  method = c(
    "Logistic regression",
    "Random forest"
  ),
  B = c(
    B_time,
    B_time
  ),
  elapsed_seconds = c(
    unname(time_logistic_boot["elapsed"]),
    unname(time_rf_boot["elapsed"])
  )
)

timing_comparison

### Convert elapsed time to minutes


timing_comparison$elapsed_minutes <-
  timing_comparison$elapsed_seconds / 60

timing_comparison


### Relative computation time


rf_time_ratio <-
  unname(time_rf_boot["elapsed"]) /
  unname(time_logistic_boot["elapsed"])

cat(
  "\nRandom-forest bootstrap took",
  round(rf_time_ratio, 2),
  "times as long as logistic-regression bootstrap.\n"
)


